language: go

go:
  - 1.8

install:
- export GITVER=$(git rev-parse HEAD)
- export VER='v1.0'-${GITVER:0:8}
- day=$(date +%Y%m%d)
- export TAG=${day}'-'${VER}
- go build -ldflags "-X main._VERSION_='$TAG'"

script:
- go test